### ISSUE TITLE
Not working with parentheses

### ISSUE THREAD

**Issue by GitHunter0** [kylebarron/vscode-jupyter-python#13]
Consider this example:
```
import pandas as pd
(
    pd.to_datetime("2011-01-07") \
    # convert to period
    .to_period(freq="W") \
    # convert back to timestamp
    .to_timestamp() 
)
```
Trying to run the block in parentheses throws this error:
![image](https://github.com/kylebarron/vscode-jupyter-python/assets/26294221/699d3153-e8f4-4516-aae6-fb39c6f705ec)

Thank you

**Comment by kylebarron** [comment]
That snippet works fine for me. You might need to check that you installed the package correctly?

https://github.com/kylebarron/vscode-jupyter-python/assets/15164633/d2ce3ab6-8b4d-4fce-85bc-1af2fd3b09de

**Comment by GitHunter0** [comment]
I restarted VScode and now it's working fine, thank you @kylebarron
