### ISSUE TITLE
Display execution time?

### ISSUE THREAD

**Issue by zachwarner** [kylebarron/vscode-jupyter-python#8]
Hey, great extension -- have been loving it so far. One small visual thing, though: the interactive window collapses the output block, hiding the execution time beneath `...`. It would be great if the execution time could display by default next to the green check. I searched preferences/settings but was unable to find any way to enable this.

**Comment by kylebarron** [comment]
I think that would be a request for upstream; this is just for sending blocks of code to be executed at once

**Comment by zachwarner** [comment]
Fair enough! I wasn't sure if this was something you could control.
